[package]
name = "rust_proxy_peer"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls-pemfile = "2.1.3"
tokio = { version = "1", features = ["full"] }
tokio-native-tls = "0.3.1"
tokio-rustls = "0.26.0"
webpki = "0.22.4"
